language: node_js
install:
  - yarn install --frozen-lockfile
script:
  - yarn build
  - yarn lint
  - yarn type-coverage
  - yarn test
  # TODO https://github.com/danielnixon/eslint-plugin-total-functions/issues/85
  # - yarn mutation-test
after_success:
  - yarn codecov
